# Generated by Django 5.2.7 on 2025-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='STARTED', max_length=20),
        ),
    ]
