# Generated by Django 5.2.7 on 2025-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_account_balance_expense_account_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(db_index=True, default='Other', max_length=100),
        ),
    ]
