# Generated by Django 5.2.7 on 2025-10-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHECKED_OUT', 'Checked Out'), ('PARTIAL_RETURN', 'Partially Returned'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CheckoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=10, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_by', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_by', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='equipment.equipmentrequest')),
            ],
            options={
                'ordering': ['-checked_out_at'],
            },
        ),
    ]
