# Generated by Django 5.2.7 on 2025-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutlog',
            name='quantity',
        ),
    ]
